--- #YAML:1.0
name:               Net-EPP-Registry-Nominet
version:            0.00
abstract:           EPP client code for Nominet
author:
    - Pete Houston (cpan@openstrike.co.uk)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    Carp:      0
    Net::EPP:  0.19
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
